# Generated by Django 5.2.12 on 2026-04-06 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created']},
        ),
    ]
